### ISSUE TITLE
why can't use the library

### ISSUE THREAD

**Issue by fers50** [CESARBR/GT521F52#5]
Hi, my again,

why I can't use the new library of GT-521F52?
when I install the library, its work like this:
pip install GT-521F52
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting GT-521F52
  Using cached https://files.pythonhosted.org/packages/19/a2/26a834ec1e2ca65389bfb5e7765291c49611531891d49a5abd24f7fd55d8/GT_521F52-1.0.0-py3-none-any.whl
Collecting pyserial>=3.4.0 (from GT-521F52)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Installing collected packages: pyserial, GT-521F52
Successfully installed GT-521F52-1.0.0 pyserial-3.4

but when I want to run the program there is some error: 
Traceback (most recent call last):
  File "examples.py", line 1, in <module>
    import GT_521F52
ImportError: No module named GT_521F52

So, I change the library in a code like this:
sudo python examples.py 
  File "examples.py", line 1
    import GT-521F52
             ^
SyntaxError: invalid syntax

that error still occurs
can you help me to fix a code?

**Comment by paulxavier86** [comment]
I got the same error

**Comment by marlonchalegre** [comment]
Yeah, my bad. I'll talk with @OtacilioN to solve this problem.

**Comment by remnt** [comment]
Hi This Is Ramesh

I got the same error, please help out 

why I can't use the new library of GT-521F52?
when I install the library, its work like this:
pip install GT-521F52
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting GT-521F52
Using cached https://files.pythonhosted.org/packages/19/a2/26a834ec1e2ca65389bfb5e7765291c49611531891d49a5abd24f7fd55d8/GT_521F52-1.0.0-py3-none-any.whl
Collecting pyserial>=3.4.0 (from GT-521F52)
Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Installing collected packages: pyserial, GT-521F52
Successfully installed GT-521F52-1.0.0 pyserial-3.4

but when I want to run the program there is some error:
Traceback (most recent call last):
File "examples.py", line 1, in
import GT_521F52
ImportError: No module named GT_521F52

So, I change the library in a code like this:
sudo python examples.py
File "examples.py", line 1
import GT-521F52
^
SyntaxError: invalid syntax

that error still occurs
can you help me to fix a code?
